language: generic
sudo: required
services:
  - docker

env:
  global:
    - ENVOY_IMAGE_NAME=envoyproxy/envoy
    - CONSUL_IMAGE_NAME=consul
    - DOCKER_HUB_USERNAME=timarenz
  matrix:
    - CONSUL_VERSION=1.5.2 ENVOY_VERSION=v1.9.1
    - CONSUL_VERSION=1.5.2 NVOY_VERSION=v1.10.0
    - CONSUL_VERSION=1.5.2 ENVOY_VERSION=v1.11.1
    - CONSUL_VERSION=1.5.3 ENVOY_VERSION=v1.9.1
    - CONSUL_VERSION=1.5.3 NVOY_VERSION=v1.10.0
    - CONSUL_VERSION=1.5.3 ENVOY_VERSION=v1.11.1
    - CONSUL_VERSION=1.6.0 ENVOY_VERSION=v1.9.1
    - CONSUL_VERSION=1.6.0 NVOY_VERSION=v1.10.0
    - CONSUL_VERSION=1.6.0 ENVOY_VERSION=v1.11.1

before_script:
  - docker pull ${ENVOY_IMAGE_NAME}:${ENVOY_VERSION}
  - docker pull ${CONSUL_IMAGE_NAME}:${CONSUL_VERSION}

script:
  - docker build --pull --tag ${DOCKER_HUB_USERNAME}/envoy-consul:${ENVOY_VERSION}_${CONSUL_VERSION} --build-arg CONSUL_IMAGE=${CONSUL_IMAGE_NAME}:${CONSUL_VERSION} --build-arg ENVOY_IMAGE=${ENVOY_IMAGE_NAME}:${ENVOY_VERSION} .

after_script:
  - docker images
