language: generic
os: linux
dist: xenial
services:
  - docker

env:
  global:
    - ENVOY_IMAGE_NAME=envoyproxy/envoy
    - CONSUL_IMAGE_NAME=consul
    - IMAGE_NAME=envoy-consul
  matrix:
    # - CONSUL_VERSION=1.3.0 ENVOY_VERSION=v1.7.0 LATEST=false
    # - CONSUL_VERSION=1.3.0 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.3.0 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.3.1 ENVOY_VERSION=v1.7.0 LATEST=false
    # - CONSUL_VERSION=1.3.1 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.3.1 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.4.0 ENVOY_VERSION=v1.7.0 LATEST=false
    # - CONSUL_VERSION=1.4.0 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.4.0 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.4.1 ENVOY_VERSION=v1.7.0 LATEST=false
    # - CONSUL_VERSION=1.4.1 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.4.1 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.4.2 ENVOY_VERSION=v1.7.0 LATEST=false
    # - CONSUL_VERSION=1.4.2 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.4.2 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.4.3 ENVOY_VERSION=v1.7.0 LATEST=false
    # - CONSUL_VERSION=1.4.3 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.4.3 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.4.4 ENVOY_VERSION=v1.7.0 LATEST=false
    # - CONSUL_VERSION=1.4.4 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.4.4 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.4.5 ENVOY_VERSION=v1.7.0 LATEST=false
    # - CONSUL_VERSION=1.4.5 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.4.5 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.5.0 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.5.0 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.5.1 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.5.1 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.5.2 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.5.2 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.5.2 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.5.2 ENVOY_VERSION=v1.11.1 LATEST=false
    # - CONSUL_VERSION=1.5.3 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.5.3 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.5.3 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.5.3 ENVOY_VERSION=v1.11.1 LATEST=false
    # - CONSUL_VERSION=1.6.0 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.6.0 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.6.0 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.6.0 ENVOY_VERSION=v1.11.1 LATEST=false
    # - CONSUL_VERSION=1.6.1 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.6.1 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.6.1 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.6.1 ENVOY_VERSION=v1.11.1 LATEST=false
    # - CONSUL_VERSION=1.6.2 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.6.2 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.6.2 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.6.2 ENVOY_VERSION=v1.11.1 LATEST=false
    # - CONSUL_VERSION=1.6.3 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.6.3 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.6.3 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.6.3 ENVOY_VERSION=v1.11.1 LATEST=false
    # - CONSUL_VERSION=1.6.4 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.6.4 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.6.4 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.6.4 ENVOY_VERSION=v1.11.1 LATEST=false
    # - CONSUL_VERSION=1.6.5 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.6.5 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.6.5 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.6.5 ENVOY_VERSION=v1.11.1 LATEST=false
    # - CONSUL_VERSION=1.6.6 ENVOY_VERSION=v1.8.0 LATEST=false
    # - CONSUL_VERSION=1.6.6 ENVOY_VERSION=v1.9.1 LATEST=false
    # - CONSUL_VERSION=1.6.6 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.6.6 ENVOY_VERSION=v1.11.1 LATEST=false
    # - CONSUL_VERSION=1.7.0 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.7.0 ENVOY_VERSION=v1.11.2 LATEST=false
    # - CONSUL_VERSION=1.7.0 ENVOY_VERSION=v1.12.2 LATEST=false
    # - CONSUL_VERSION=1.7.0 ENVOY_VERSION=v1.12.3 LATEST=false
    # - CONSUL_VERSION=1.7.0 ENVOY_VERSION=v1.13.0 LATEST=false
    # - CONSUL_VERSION=1.7.0 ENVOY_VERSION=v1.13.1 LATEST=false
    # - CONSUL_VERSION=1.7.1 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.7.1 ENVOY_VERSION=v1.11.2 LATEST=false
    # - CONSUL_VERSION=1.7.1 ENVOY_VERSION=v1.12.2 LATEST=false
    # - CONSUL_VERSION=1.7.1 ENVOY_VERSION=v1.12.3 LATEST=false
    # - CONSUL_VERSION=1.7.1 ENVOY_VERSION=v1.13.0 LATEST=false
    # - CONSUL_VERSION=1.7.1 ENVOY_VERSION=v1.13.1 LATEST=false
    # - CONSUL_VERSION=1.7.2 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.7.2 ENVOY_VERSION=v1.11.2 LATEST=false
    # - CONSUL_VERSION=1.7.2 ENVOY_VERSION=v1.12.2 LATEST=false
    # - CONSUL_VERSION=1.7.2 ENVOY_VERSION=v1.12.3 LATEST=false
    # - CONSUL_VERSION=1.7.2 ENVOY_VERSION=v1.13.0 LATEST=false
    # - CONSUL_VERSION=1.7.2 ENVOY_VERSION=v1.13.1 LATEST=false
    # - CONSUL_VERSION=1.7.3 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.7.3 ENVOY_VERSION=v1.11.2 LATEST=false
    # - CONSUL_VERSION=1.7.3 ENVOY_VERSION=v1.12.2 LATEST=false
    # - CONSUL_VERSION=1.7.3 ENVOY_VERSION=v1.12.3 LATEST=false
    # - CONSUL_VERSION=1.7.3 ENVOY_VERSION=v1.13.0 LATEST=false
    # - CONSUL_VERSION=1.7.3 ENVOY_VERSION=v1.13.1 LATEST=false
    # - CONSUL_VERSION=1.7.4 ENVOY_VERSION=v1.10.0 LATEST=false
    # - CONSUL_VERSION=1.7.4 ENVOY_VERSION=v1.11.2 LATEST=false
    # - CONSUL_VERSION=1.7.4 ENVOY_VERSION=v1.12.3 LATEST=false
    # - CONSUL_VERSION=1.7.4 ENVOY_VERSION=v1.13.1 LATEST=true
    # - CONSUL_VERSION=1.8.0-beta1 ENVOY_VERSION=v1.11.2 LATEST=false
    # - CONSUL_VERSION=1.8.0-beta1 ENVOY_VERSION=v1.12.3 LATEST=false
    # - CONSUL_VERSION=1.8.0-beta1 ENVOY_VERSION=v1.13.1 LATEST=false
    # - CONSUL_VERSION=1.8.0-beta1 ENVOY_VERSION=v1.14.1 LATEST=false
    # - CONSUL_VERSION=1.8.0-beta2 ENVOY_VERSION=v1.11.2 LATEST=false
    # - CONSUL_VERSION=1.8.0-beta2 ENVOY_VERSION=v1.12.3 LATEST=false
    # - CONSUL_VERSION=1.8.0-beta2 ENVOY_VERSION=v1.13.1 LATEST=false
    # - CONSUL_VERSION=1.8.0-beta2 ENVOY_VERSION=v1.14.1 LATEST=false
    # - CONSUL_VERSION=1.8.0-rc1 ENVOY_VERSION=v1.11.2 LATEST=false
    # - CONSUL_VERSION=1.8.0-rc1 ENVOY_VERSION=v1.12.3 LATEST=false
    # - CONSUL_VERSION=1.8.0-rc1 ENVOY_VERSION=v1.13.1 LATEST=false
    # - CONSUL_VERSION=1.8.0-rc1 ENVOY_VERSION=v1.14.1 LATEST=false
    - CONSUL_VERSION=1.8.0 ENVOY_VERSION=v1.11.2 LATEST=false
    - CONSUL_VERSION=1.8.0 ENVOY_VERSION=v1.12.4 LATEST=false
    - CONSUL_VERSION=1.8.0 ENVOY_VERSION=v1.13.2 LATEST=false
    - CONSUL_VERSION=1.8.0 ENVOY_VERSION=v1.14.2 LATEST=true

before_script:
  - docker pull ${ENVOY_IMAGE_NAME}:${ENVOY_VERSION}
  - docker pull ${CONSUL_IMAGE_NAME}:${CONSUL_VERSION}

script:
  - docker build --pull --tag ${IMAGE_NAME} --build-arg CONSUL_IMAGE=${CONSUL_IMAGE_NAME}:${CONSUL_VERSION} --build-arg ENVOY_IMAGE=${ENVOY_IMAGE_NAME}:${ENVOY_VERSION} .
  - docker run -it --entrypoint /bin/consul ${IMAGE_NAME} version
  - docker run -it --entrypoint /usr/local/bin/envoy ${IMAGE_NAME} --version

before_deploy:
  - docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_PASSWORD}"
  - docker tag "${IMAGE_NAME}" "${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${ENVOY_VERSION}_${CONSUL_VERSION}"
  - |
    if (${LATEST}); then
      docker tag "${IMAGE_NAME}" "${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:latest"
    fi
deploy:
  provider: script
  script: bash push.sh
  on:
    branch: master
