name: 'build-docker'

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        consul_version:
          - "1.3.0"
          - "1.3.1"
          - "1.4.0"
          - "1.4.1"
          - "1.4.2"
          - "1.4.3"
          - "1.4.5"
          - "1.5.0"
          - "1.5.1"
          - "1.5.2"
          - "1.5.3"
          - "1.6.0"
          - "1.6.1"
          - "1.6.2"
          - "1.6.3"
          - "1.6.4"
          - "1.6.5"
          - "1.6.6"
          - "1.6.7"
          - "1.6.8"
          - "1.6.10"
          - "1.7.0"
          - "1.7.1"
          - "1.7.2"
          - "1.7.3"
          - "1.7.4"
          - "1.7.5"
          - "1.7.6"
          - "1.7.7"
          - "1.7.8"
          - "1.7.9"
          - "1.7.10"
          - "1.7.11"
          - "1.7.12"
          - "1.8.0"
          - "1.8.1"
          - "1.8.2"
          - "1.8.3"
          - "1.8.4"
          - "1.8.5"
          - "1.8.6"
          - "1.8.7"
          - "1.8.8"
          - "1.8.9"
          - "1.9.0"
          - "1.9.1"
          - "1.9.2"
          - "1.9.3"
        consul_13_14_envoy_version:
          - "1.7.0"
          - "1.8.0"
          - "1.9.1"
        consul_15_envoy_version:
          - "1.8.0"
          - "1.9.1"
        consul_152_16_envoy_version:
          - "1.8.0"
          - "1.9.1"
          - "1.10.0"
          - "1.11.1"
        consul_17_envoy_version:
          - "1.10.0"
          - "1.11.2"
          - "1.12.7"
          - "1.13.6"
        consul_18_envoy_version:
          - "1.11.2"
          - "1.12.7"
          - "1.13.6"
          - "1.14.5"
        consul_19_envoy_version:
          - "1.13.6"
          - "1.14.5"
          - "1.15.2"
          - "1.16.0"
  
    steps:
      - name: Get branch name
        if: contains(${{ matrix.consul_version }}, '1.3.') || contains(${{ matrix.consul_version }}, '1.4.')
        run: >
          echo "consul: $${{ matrix.consul_version }} ... envoy: $${{ matrix.consul_13_14_envoy_version }}"
        
          
