name: 'consul-1-7'

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        consul_version:
          - "1.7.0"
          - "1.7.1"
          - "1.7.2"
          - "1.7.3"
          - "1.7.4"
          - "1.7.5"
          - "1.7.6"
          - "1.7.7"
          - "1.7.8"
          - "1.7.9"
          - "1.7.10"
          - "1.7.11"
          - "1.7.12"
        envoy_version:
          - "1.10.0"
          - "1.11.2"
          - "1.12.7"
          - "1.13.6"
  
    steps:
      - name: Versions
        run: >
          echo "consul: $${{ matrix.consul_version }} ... envoy: $${{ matrix.envoy_version }}"
        
          
