name: 'consul-1-8'

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        consul_version:
          - "1.8.0"
          - "1.8.1"
          - "1.8.2"
          - "1.8.3"
          - "1.8.4"
          - "1.8.5"
          - "1.8.6"
          - "1.8.7"
          - "1.8.8"
          - "1.8.9"
        envoy_version:
          - "1.11.2"
          - "1.12.7"
          - "1.13.6"
          - "1.14.5"
  
    steps:
      - name: Versions
        run: >
          echo "consul: $${{ matrix.consul_version }} ... envoy: $${{ matrix.envoy_version }}"
        
          
